window.KAZDOURA_EXTRA_LANDMARKS=[
{n:['خان أسعد باشا','Khan As’ad Pasha','Khan As’ad Pasha'],d:['خان عثماني تاريخي بارز في دمشق القديمة.','Historischer osmanischer Khan in der Altstadt.','Historic Ottoman khan in Old Damascus.'],lat:33.5088,lng:36.3096},
{n:['قلعة دمشق','Zitadelle von Damaskus','Citadel of Damascus'],d:['قلعة تاريخية على الطرف الغربي للمدينة القديمة.','Historische Zitadelle am Westrand der Altstadt.','Historic citadel on the western edge of the Old City.'],lat:33.5117,lng:36.3019},
{n:['المتحف الوطني بدمشق','Nationalmuseum Damaskus','National Museum of Damascus'],d:['من أهم متاحف سوريا.','Eines der wichtigsten Museen Syriens.','One of Syria’s most important museums.'],lat:33.5126,lng:36.2904},
{n:['الشارع المستقيم','Gerade Straße','Straight Street'],d:['محور تاريخي يعود تخطيطه للعصر الروماني.','Historische Achse mit römischen Ursprüngen.','Historic axis with Roman origins.'],lat:33.5095,lng:36.315},
{n:['باب شرقي','Bab Sharqi','Bab Sharqi'],d:['باب تاريخي عند الطرف الشرقي للشارع المستقيم.','Historisches Stadttor.','Historic city gate.'],lat:33.5093,lng:36.3178},
{n:['باب توما','Bab Tuma','Bab Tuma'],d:['باب تاريخي في شمال شرق المدينة القديمة.','Historisches Stadttor.','Historic city gate.'],lat:33.5144,lng:36.3159},
{n:['باب كيسان','Bab Kisan','Bab Kisan'],d:['باب تاريخي مرتبط بتقليد القديس بولس.','Historisches Tor mit Paulus-Tradition.','Historic gate associated with Saint Paul tradition.'],lat:33.5058,lng:36.3176},
{n:['باب الصغير','Bab al-Saghir','Bab al-Saghir'],d:['أحد أبواب دمشق التاريخية الجنوبية.','Historisches südliches Stadttor.','Historic southern city gate.'],lat:33.5037,lng:36.3067},
{n:['باب الجابية','Bab al-Jabiya','Bab al-Jabiya'],d:['باب تاريخي غرب المدينة القديمة.','Historisches westliches Stadttor.','Historic western city gate.'],lat:33.5086,lng:36.3018},
{n:['باب السلام','Bab al-Salam','Bab al-Salam'],d:['باب تاريخي في شمال سور دمشق القديمة.','Historisches nördliches Stadttor.','Historic northern city gate.'],lat:33.5161,lng:36.3127},
{n:['باب الفراديس','Bab al-Faradis','Bab al-Faradis'],d:['باب تاريخي في القسم الشمالي من السور.','Historisches Stadttor.','Historic city gate.'],lat:33.516,lng:36.307},
{n:['التكية السليمانية','Tekkiye-Süleymaniye','Sulaymaniyah Takiyya'],d:['مجمع عثماني من القرن السادس عشر.','Osmanischer Komplex des 16. Jahrhunderts.','16th-century Ottoman complex.'],lat:33.5128,lng:36.2922},
{n:['بيت حنانيا','Haus des Hananias','House of Ananias'],d:['موقع مسيحي تاريخي في دمشق القديمة.','Historischer christlicher Ort.','Historic Christian site.'],lat:33.5091,lng:36.316},
{n:['ضريح صلاح الدين الأيوبي','Saladin-Mausoleum','Mausoleum of Saladin'],d:['ضريح تاريخي بجوار الجامع الأموي.','Historisches Mausoleum neben der Umayyaden-Moschee.','Historic mausoleum beside the Umayyad Mosque.'],lat:33.5121,lng:36.3061},
{n:['البيمارستان النوري','Nur-al-Din-Bimaristan','Nur al-Din Bimaristan'],d:['بيمارستان تاريخي من القرن الثاني عشر.','Historisches Hospital des 12. Jahrhunderts.','Historic 12th-century hospital.'],lat:33.5102,lng:36.3035},
{n:['المدرسة العادلية الكبرى','Al-Adiliyah-Madrasa','Al-Adiliyah Madrasa'],d:['مدرسة أيوبيّة تاريخية قرب الجامع الأموي.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.513,lng:36.3054},
{n:['المدرسة الظاهرية','Az-Zahiriyah-Madrasa','Al-Zahiriyah Madrasa'],d:['مجمع مملوكي تاريخي يضم مكتبة وضريحاً.','Historischer mamlukischer Komplex.','Historic Mamluk complex.'],lat:33.5128,lng:36.3058},
{n:['المدرسة النورية الكبرى','An-Nuriyah al-Kubra','Al-Nuriyah al-Kubra Madrasa'],d:['مدرسة تاريخية مرتبطة بنور الدين زنكي.','Historische Madrasa.','Historic madrasa.'],lat:33.511,lng:36.3046},
{n:['جامع السنانية','Sinan-Pascha-Moschee','Sinan Pasha Mosque'],d:['جامع عثماني تاريخي.','Historische osmanische Moschee.','Historic Ottoman mosque.'],lat:33.5078,lng:36.3017},
{n:['الجامع المعلق','Al-Muallaq-Moschee','Al-Muallaq Mosque'],d:['جامع تاريخي يتميز بارتفاعه عن مستوى الطريق.','Historische Moschee.','Historic mosque.'],lat:33.5154,lng:36.3079},
{n:['كنيسة القديس بولس عند باب كيسان','Pauluskapelle am Bab Kisan','Chapel of Saint Paul at Bab Kisan'],d:['كنيسة مرتبطة بتقليد هروب القديس بولس من دمشق.','Historische Pauluskapelle.','Historic chapel associated with Saint Paul.'],lat:33.5058,lng:36.3176},
{n:['الكنيسة المريمية','Mariamitische Kathedrale','Mariamite Cathedral'],d:['كاتدرائية تاريخية في دمشق القديمة.','Historische Kathedrale.','Historic cathedral.'],lat:33.5114,lng:36.3124},
{n:['مكتب عنبر','Maktab Anbar','Maktab Anbar'],d:['بيت دمشقي تاريخي تحول إلى مدرسة ثم مركز ثقافي.','Historisches Damascener Haus.','Historic Damascene house.'],lat:33.5086,lng:36.3119},
{n:['قصر النعسان','Naasan-Palast','Naasan Palace'],d:['بيت دمشقي تاريخي تقليدي.','Traditionelles historisches Haus.','Traditional historic house.'],lat:33.5106,lng:36.311},
{n:['حمام نور الدين','Hammam Nur ad-Din','Hammam Nur al-Din'],d:['حمام دمشقي تاريخي في منطقة البزورية.','Historisches Hammam.','Historic hammam.'],lat:33.5094,lng:36.307},
{n:['خان سليمان باشا','Khan Sulayman Pasha','Khan Sulayman Pasha'],d:['خان عثماني تاريخي في المدينة القديمة.','Historischer osmanischer Khan.','Historic Ottoman khan.'],lat:33.5099,lng:36.308},
{n:['سور دمشق القديمة','Stadtmauer von Damaskus','Old Damascus City Wall'],d:['بقايا سور دمشق التاريخي.','Historische Stadtmauer.','Historic city wall.'],lat:33.515,lng:36.312},
{n:['جامع السادات','Al-Sadat-Moschee','Al-Sadat Mosque'],d:['جامع تاريخي في دمشق القديمة.','Historische Moschee.','Historic mosque.'],lat:33.5127,lng:36.3093},
{n:['جامع التوبة','At-Tawbah-Moschee','Al-Tawbah Mosque'],d:['جامع تاريخي في حي العقيبة.','Historische Moschee.','Historic mosque.'],lat:33.521,lng:36.307},
{n:['جامع مراد باشا','Murad-Pascha-Moschee','Murad Pasha Mosque'],d:['جامع عثماني تاريخي.','Historische osmanische Moschee.','Historic Ottoman mosque.'],lat:33.5028,lng:36.2988},
{n:['جامع درويش باشا','Darwish-Pascha-Moschee','Darwish Pasha Mosque'],d:['جامع عثماني تاريخي.','Historische osmanische Moschee.','Historic Ottoman mosque.'],lat:33.5094,lng:36.3003},
{n:['جامع يلبغا','Yalbugha-Moschee','Yalbugha Mosque'],d:['موقع جامع مملوكي تاريخي ارتبط بساحة المرجة.','Historischer Moscheestandort.','Historic mosque site.'],lat:33.5137,lng:36.299},
{n:['المدرسة الجقمقية','Al-Jaqmaqiyah-Madrasa','Al-Jaqmaqiyah Madrasa'],d:['مدرسة مملوكية تاريخية قرب الجامع الأموي.','Historische mamlukische Madrasa.','Historic Mamluk madrasa.'],lat:33.512,lng:36.3052},
{n:['المدرسة العزيزية','Al-Aziziyah-Madrasa','Al-Aziziyah Madrasa'],d:['مدرسة أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5123,lng:36.3057},
{n:['المدرسة الركنية','Ar-Rukniyah-Madrasa','Al-Rukniyah Madrasa'],d:['مدرسة أيوبيّة تاريخية في دمشق.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5262,lng:36.2938},
{n:['قصر الحير الغربي – واجهة المتحف','Qasr al-Hayr al-Gharbi Fassade','Qasr al-Hayr al-Gharbi façade'],d:['واجهة أموية أعيد تركيبها عند المتحف الوطني.','Umayyadische Fassade am Nationalmuseum.','Umayyad façade at the National Museum.'],lat:33.5126,lng:36.2904},
{n:['بيت خالد العظم','Khalid-al-Azm-Haus','Khalid al-Azm House'],d:['أحد البيوت الدمشقية التاريخية.','Historisches Damascener Haus.','Historic Damascene house.'],lat:33.5098,lng:36.311},
{n:['بيت السباعي','As-Sibai-Haus','Al-Sibai House'],d:['بيت دمشقي تقليدي في المدينة القديمة.','Traditionelles Damascener Haus.','Traditional Damascene house.'],lat:33.5097,lng:36.312},
{n:['حمام البكري','Al-Bakri-Hammam','Al-Bakri Hammam'],d:['حمام دمشقي تقليدي تاريخي.','Historisches Hammam.','Historic hammam.'],lat:33.5079,lng:36.304},
{n:['دار الحديث الأشرفية','Dar al-Hadith al-Aschrafiyya','Dar al-Hadith al-Ashrafiyya'],d:['مدرسة حديث أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.51194,lng:36.30337},
{n:['المدرسة الأتابكية','Atabakiyya-Madrasa','Atabakiyya Madrasa'],d:['مدرسة أيوبيّة في حي الصالحية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5272,lng:36.2848},
{n:['المدرسة المرشدية','Murshidiyya-Madrasa','Murshidiyya Madrasa'],d:['مدرسة جنائزية أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5276,lng:36.2852},
{n:['المدرسة الماردانية / جامع الجسر الأبيض','Maridaniyya-Madrasa','Maridaniyya Madrasa'],d:['مدرسة أيوبيّة تاريخية تُعرف اليوم بجامع الجسر الأبيض.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.52455,lng:36.28808},
{n:['المدرسة الجهاركسية','Jaharkasiyya-Madrasa','Jaharkasiyya Madrasa'],d:['مدرسة وضريح أيوبي تاريخي في الصالحية.','Historische Madrasa und Grabstätte.','Historic madrasa and tomb.'],lat:33.52848,lng:36.28658},
{n:['المدرسة الصاحبية','Sahibiyya-Madrasa','Sahibiyya Madrasa'],d:['مدرسة أيوبيّة تاريخية في الصالحية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.531913,lng:36.291995},
{n:['جامع الأقصاب','Al-Aqsab-Moschee','Al-Aqsab Mosque'],d:['جامع تاريخي شمال المدينة القديمة.','Historische Moschee.','Historic mosque.'],lat:33.5196,lng:36.3092},
{n:['المدرسة الشامية البرانية','Schamiyya al-Barraniyya','Al-Shamiyya al-Barraniyya'],d:['مدرسة أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5178,lng:36.2996},
{n:['المدرسة الشامية الجوانية','Schamiyya al-Juwwaniyya','Al-Shamiyya al-Juwwaniyya'],d:['مدرسة أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.512,lng:36.3039},
{n:['المدرسة الكاملية','Kamiliyya-Madrasa','Al-Kamiliyya Madrasa'],d:['مدرسة أيوبيّة تاريخية.','Historische ayyubidische Madrasa.','Historic Ayyubid madrasa.'],lat:33.5147,lng:36.3048},
{n:['المدرسة الدماغية','Dumaghiyya-Madrasa','Al-Dumaghiyya Madrasa'],d:['مدرسة تاريخية من العصر الأيوبي.','Historische Madrasa.','Historic madrasa.'],lat:33.5127,lng:36.3034},
{n:['المدرسة العذراوية','Adhrawiyya-Madrasa','Al-Adhrawiyya Madrasa'],d:['مدرسة تاريخية من مدارس دمشق.','Historische Madrasa.','Historic madrasa.'],lat:33.5135,lng:36.3032},
{n:['المدرسة القليجية','Qilijiyya-Madrasa','Al-Qilijiyya Madrasa'],d:['مدرسة وضريح تاريخيان.','Historische Madrasa und Grabstätte.','Historic madrasa and tomb.'],lat:33.5168,lng:36.2999},
{n:['المدرسة الخاتونية','Khatuniyya-Madrasa','Al-Khatuniyya Madrasa'],d:['مدرسة تاريخية من العصر الأيوبي.','Historische Madrasa.','Historic madrasa.'],lat:33.5162,lng:36.2994},
{n:['تربة خاتون','Khatun-Mausoleum','Khatun Mausoleum'],d:['تربة تاريخية في دمشق.','Historische Grabstätte.','Historic tomb.'],lat:33.5159,lng:36.2996},
{n:['تربة الفرنتي','Al-Faranti-Mausoleum','Al-Faranti Mausoleum'],d:['ضريح تاريخي في الصالحية.','Historisches Mausoleum.','Historic mausoleum.'],lat:33.5275,lng:36.2851},
{n:['جامع الحنابلة','Hanbaliten-Moschee','Hanbali Mosque'],d:['جامع تاريخي بارز في حي الصالحية.','Historische Moschee in al-Salihiyya.','Historic mosque in al-Salihiyya.'],lat:33.5307,lng:36.2911},
{n:['جامع تنكز','Tankiz-Moschee','Tankiz Mosque'],d:['جامع مملوكي تاريخي.','Historische mamlukische Moschee.','Historic Mamluk mosque.'],lat:33.5096,lng:36.2936},
{n:['جامع الورد','Al-Ward-Moschee','Al-Ward Mosque'],d:['جامع عثماني تاريخي في ساروجة.','Historische osmanische Moschee.','Historic Ottoman mosque.'],lat:33.5169,lng:36.2968},
{n:['جامع السنجقدار','Sinjidar-Moschee','Sinjidar Mosque'],d:['جامع تاريخي قرب مركز دمشق القديم.','Historische Moschee.','Historic mosque.'],lat:33.5127,lng:36.2979},
{n:['جامع هشام','Hisham-Moschee','Hisham Mosque'],d:['جامع تاريخي ضمن النسيج الدمشقي.','Historische Moschee.','Historic mosque.'],lat:33.5108,lng:36.3024},
{n:['خان جقمق','Khan Jaqmaq','Khan Jaqmaq'],d:['خان مملوكي تاريخي.','Historischer mamlukischer Khan.','Historic Mamluk khan.'],lat:33.5116,lng:36.3053},
{n:['خان الحرير','Khan al-Harir','Khan al-Harir'],d:['خان تاريخي ارتبط بتجارة الحرير.','Historischer Seiden-Khan.','Historic silk-trade khan.'],lat:33.5109,lng:36.3072},
{n:['خان الجمرك','Khan al-Jumruk','Khan al-Jumruk'],d:['خان تجاري تاريخي في أسواق دمشق.','Historischer Handelshof.','Historic commercial khan.'],lat:33.5099,lng:36.3077},
{n:['المدرسة الأمينية','Aminiyya-Madrasa','Al-Aminiyya Madrasa'],d:['مدرسة تاريخية من مدارس دمشق القديمة.','Historische Madrasa.','Historic madrasa.'],lat:33.5131,lng:36.3041}
];