window.KAZDOURA_EXTRA_LANDMARKS=[
{n:['المدرسة الصاحبية','Sahibiyya-Madrasa','Sahibiyya Madrasa'],d:['مدرسة أيوبيّة تاريخية في الصالحية، شُيّدت بين 1233 و1245.','Historische ayyubidische Madrasa in al-Salihiyya, erbaut 1233–1245.','Historic Ayyubid madrasa in al-Salihiyya, built 1233–1245.'],lat:33.531913,lng:36.291995,imgs:['https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent('Damascus Al-Salihiyah Madrasa Sahibiye 4898.jpg'),'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent('Damascus Al-Salihiyah Madrasa Sahibiye 4897.jpg')]},
{n:['المدرسة الركنية – صور إضافية','Rukniyya-Madrasa','Rukniyya Madrasa'],d:['مدرسة وضريح أيوبي أُنشئ سنة 1224 في منطقة الصالحية.','Ayyubidische Madrasa und Grabstätte von 1224 in al-Salihiyya.','Ayyubid madrasa and tomb founded in 1224 in al-Salihiyya.'],lat:33.5262,lng:36.2938,imgs:['https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent('Damascus Al- Salihiyah - Madrasa Rukniye 4913.jpg'),'https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent('Damascus Al- Salihiyah - Madrasa Rukniye 4904.jpg')]},
{n:['جامع الأقصاب','Al-Aqsab-Moschee','Al-Aqsab Mosque'],d:['جامع تاريخي شمال المدينة المسوّرة، تعود جذوره إلى العصر الأيوبي وتعرّض لتوسعات مملوكية.','Historische Moschee nördlich der Altstadtmauer mit ayyubidischen Ursprüngen und mamlukischen Erweiterungen.','Historic mosque north of the walled city with Ayyubid origins and Mamluk expansions.'],lat:33.5196,lng:36.3092},
{n:['المدرسة الشامية البرانية','Schamiyya al-Barraniyya','Al-Shamiyya al-Barraniyya'],d:['مدرسة أيوبيّة تاريخية من مدارس دمشق خارج السور.','Historische ayyubidische Madrasa außerhalb der Stadtmauer.','Historic Ayyubid madrasa outside the city wall.'],lat:33.5178,lng:36.2996},
{n:['المدرسة الشامية الجوانية','Schamiyya al-Juwwaniyya','Al-Shamiyya al-Juwwaniyya'],d:['مدرسة أيوبيّة تاريخية ضمن النسيج القديم لدمشق.','Historische ayyubidische Madrasa im alten Stadtgefüge von Damaskus.','Historic Ayyubid madrasa in the old urban fabric of Damascus.'],lat:33.512,lng:36.3039},
{n:['المدرسة الكاملية','Kamiliyya-Madrasa','Al-Kamiliyya Madrasa'],d:['مدرسة أيوبيّة تاريخية مرتبطة بعمارة دمشق في القرن الثالث عشر.','Historische ayyubidische Madrasa des 13. Jahrhunderts.','Historic 13th-century Ayyubid madrasa.'],lat:33.5147,lng:36.3048},
{n:['المدرسة الدماغية','Dumaghiyya-Madrasa','Al-Dumaghiyya Madrasa'],d:['مدرسة تاريخية من منشآت دمشق في العصر الأيوبي.','Historische Madrasa aus ayyubidischer Zeit.','Historic madrasa from the Ayyubid period.'],lat:33.5127,lng:36.3034},
{n:['المدرسة العذراوية','Adhrawiyya-Madrasa','Al-Adhrawiyya Madrasa'],d:['مدرسة تاريخية من مدارس دمشق الإسلامية.','Historische islamische Madrasa in Damaskus.','Historic Islamic madrasa in Damascus.'],lat:33.5135,lng:36.3032},
{n:['المدرسة القليجية','Qilijiyya-Madrasa','Al-Qilijiyya Madrasa'],d:['مدرسة وضريح تاريخيان من معالم دمشق الوسيطة.','Historische Madrasa und Grabstätte des mittelalterlichen Damaskus.','Historic madrasa and tomb of medieval Damascus.'],lat:33.5168,lng:36.2999},
{n:['المدرسة الخاتونية','Khatuniyya-Madrasa','Al-Khatuniyya Madrasa'],d:['مدرسة تاريخية ارتبطت برعاية نساء من البيت الأيوبي.','Historische Madrasa, verbunden mit weiblicher ayyubidischer Patronage.','Historic madrasa associated with female Ayyubid patronage.'],lat:33.5162,lng:36.2994},
{n:['تربة خاتون','Khatun-Mausoleum','Khatun Mausoleum'],d:['تربة تاريخية ضمن مجموعة المنشآت الجنائزية في دمشق.','Historische Grabstätte innerhalb der Damaskener Mausoleumsarchitektur.','Historic tomb within Damascus’s funerary architecture.'],lat:33.5159,lng:36.2996},
{n:['تربة الفرنتي','Al-Faranti-Mausoleum','Al-Faranti Mausoleum'],d:['ضريح تاريخي في الصالحية يظهر ضمن مجموعة مدارس وأضرحة الحي الأيوبي.','Historisches Mausoleum im ayyubidisch geprägten Viertel al-Salihiyya.','Historic mausoleum among the Ayyubid monuments of al-Salihiyya.'],lat:33.5275,lng:36.2851,imgs:['https://commons.wikimedia.org/wiki/Special:Redirect/file/'+encodeURIComponent('Damascus Al-Salihiyah - Madrasa Atabakiye (farthest) Madrasa Murshidiye (medium) Mausoleum al- Faranti (near) 4803.jpg')]},
{n:['جامع الحنابلة','Hanbaliten-Moschee','Hanbali Mosque'],d:['جامع تاريخي بارز في حي الصالحية، ارتبط بنشأة الحي العلمية والدينية.','Bedeutende historische Moschee in al-Salihiyya.','Major historic mosque in al-Salihiyya.'],lat:33.5307,lng:36.2911},
{n:['جامع تنكز','Tankiz-Moschee','Tankiz Mosque'],d:['جامع مملوكي تاريخي في دمشق ارتبط بالأمير تنكز.','Historische mamlukische Moschee, verbunden mit Emir Tankiz.','Historic Mamluk mosque associated with Emir Tankiz.'],lat:33.5096,lng:36.2936},
{n:['جامع الورد','Al-Ward-Moschee','Al-Ward Mosque'],d:['جامع عثماني تاريخي في منطقة سوق ساروجة.','Historische osmanische Moschee im Gebiet Suq Saruja.','Historic Ottoman mosque in the Suq Saruja area.'],lat:33.5169,lng:36.2968},
{n:['جامع السنجقدار','Sinjidar-Moschee','Sinjidar Mosque'],d:['جامع تاريخي في منطقة السنجقدار قرب مركز دمشق القديم.','Historische Moschee im Viertel al-Sinjudar nahe dem alten Zentrum.','Historic mosque in al-Sinjudar near the old center of Damascus.'],lat:33.5127,lng:36.2979},
{n:['جامع هشام','Hisham-Moschee','Hisham Mosque'],d:['جامع تاريخي ضمن النسيج العمراني التقليدي لدمشق.','Historische Moschee im traditionellen Stadtgefüge von Damaskus.','Historic mosque within Damascus’s traditional urban fabric.'],lat:33.5108,lng:36.3024},
{n:['خان جقمق','Khan Jaqmaq','Khan Jaqmaq'],d:['خان مملوكي تاريخي من خانات دمشق التجارية.','Historische mamlukische Karawanserei von Damaskus.','Historic Mamluk caravanserai of Damascus.'],lat:33.5116,lng:36.3053},
{n:['خان الحرير','Khan al-Harir','Khan al-Harir'],d:['خان تاريخي ارتبط بتجارة الحرير والمنسوجات في دمشق.','Historischer Khan des Seiden- und Textilhandels.','Historic khan associated with silk and textile trade.'],lat:33.5109,lng:36.3072},
{n:['خان الجمرك','Khan al-Jumruk','Khan al-Jumruk'],d:['خان تجاري تاريخي في قلب أسواق دمشق القديمة.','Historischer Handelshof im Herzen der alten Souqs.','Historic commercial khan in the heart of the old souqs.'],lat:33.5099,lng:36.3077}
];

/* Safe category expansion: runs after the main page has created `places`. */
setTimeout(()=>{try{
const X=(n,de,en,ar,dd,ed,lat,lng,imgs)=>({n:[n,de,en],d:[ar,dd,ed],lat,lng,imgs});
const R='https://commons.wikimedia.org/wiki/Special:Redirect/file/'; const P=(...f)=>f.map(x=>R+encodeURIComponent(x));
const add=(key,items)=>{const seen=new Set(places[key].map(x=>x.n[0]));items.forEach(x=>{if(!seen.has(x.n[0]))places[key].push(x)})};
add('cafes',[
X('مقهى الروضة','Café Al-Rawda','Al-Rawda Café','مقهى دمشقي تاريخي افتتح في أواخر ثلاثينيات القرن العشرين في شارع العابد، واشتهر كملتقى للكتّاب والصحفيين والفنانين.','Historisches Damaskener Café aus den späten 1930er-Jahren in der Al-Abed-Straße, bekannt als Treffpunkt von Schriftstellern, Journalisten und Künstlern.','Historic Damascus café dating to the late 1930s on Al-Abed Street, long known as a meeting place for writers, journalists and artists.',33.5171,36.2946),
X('مقهى الهافانا','Havana Café','Havana Café','مقهى دمشقي تاريخي في وسط المدينة، معروف بجلساته التقليدية والقهوة وألعاب الطاولة.','Historisches Café im Zentrum von Damaskus mit traditioneller Atmosphäre, Kaffee und Brettspielen.','Historic central Damascus café known for its traditional atmosphere, coffee and table games.',33.515,36.294)
]);
add('markets',[
X('سوق القباقبية','Souq al-Qabaqibiyya','Souq al-Qabaqibiyya','سوق حرفي تاريخي في دمشق القديمة، ارتبط بصناعة وبيع القباقيب الخشبية والحرف التقليدية.','Historischer Handwerksmarkt der Altstadt, traditionell mit Holzpantoffeln und Kunsthandwerk verbunden.','Historic Old Damascus craft market traditionally associated with wooden clogs and handicrafts.',33.5107,36.3067),
X('سوق السروجية','Souq al-Surujiyah','Souq al-Surujiyah','سوق دمشقي تاريخي عُرف بصناعة السروج والمنتجات الجلدية ومستلزمات الخيل.','Historischer Damaskener Markt für Sattlerwaren, Lederprodukte und Reitzubehör.','Historic Damascus market known for saddlery, leather goods and equestrian equipment.',33.5154,36.2995),
X('سوق الخياطين','Schneidermarkt','Tailors’ Souq','سوق تقليدي ضمن شبكة أسواق دمشق القديمة ارتبط بالخياطة والأقمشة.','Traditioneller Markt im Netz der Altstadt-Souqs, verbunden mit Schneiderei und Stoffen.','Traditional market in the Old City souq network associated with tailoring and textiles.',33.5104,36.306),
X('سوق القيشاني','Souq al-Qishani','Souq al-Qishani','سوق صغير تاريخي ضمن أسواق المدينة القديمة والحرف التقليدية.','Kleiner historischer Markt innerhalb der traditionellen Altstadt-Souqs.','Small historic market within the traditional Old City souqs.',33.5106,36.307)
]);
const s=document.createElement('script');s.src='damascus-extra-places.js?v=1';s.onload=()=>{try{add('restaurants',window.KAZDOURA_EXTRA_PLACES?.restaurants||[]);if(document.getElementById('damascus')?.classList.contains('active'))city();}catch(e){console.warn('Kazdoura restaurant merge',e)}};document.head.appendChild(s);
if(document.getElementById('damascus')?.classList.contains('active'))city();
}catch(e){console.warn('Kazdoura extra categories',e)}},0);
